Traceback (most recent call last):
  File "/Users/shakidi/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/shakidi/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/shakidi/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/shakidi/opt/anaconda3/envs/myenv/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/shakidi/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/shakidi/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/shakidi/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df.plot(kind='scatter', x='mass', y='diameter', grid=True)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m~/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/indexes/base.py:3805[0m, in [0;36mIndex.get_loc[0;34m(self, key)[0m
[1;32m   3804[0m [38;5;28;01mtry[39;00m:
[0;32m-> 3805[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_engine[49m[38;5;241;43m.[39;49m[43mget_loc[49m[43m([49m[43mcasted_key[49m[43m)[49m
[1;32m   3806[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:

File [0;32mindex.pyx:167[0m, in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

File [0;32mindex.pyx:196[0m, in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

File [0;32mpandas/_libs/hashtable_class_helper.pxi:7081[0m, in [0;36mpandas._libs.hashtable.PyObjectHashTable.get_item[0;34m()[0m

File [0;32mpandas/_libs/hashtable_class_helper.pxi:7089[0m, in [0;36mpandas._libs.hashtable.PyObjectHashTable.get_item[0;34m()[0m

[0;31mKeyError[0m: 'mass'

The above exception was the direct cause of the following exception:

[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[29], line 1[0m
[0;32m----> 1[0m [43mdf[49m[38;5;241;43m.[39;49m[43mplot[49m[43m([49m[43mkind[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mscatter[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mx[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mmass[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43my[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mdiameter[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mgrid[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m

File [0;32m~/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/pandas/plotting/_core.py:975[0m, in [0;36mPlotAccessor.__call__[0;34m(self, *args, **kwargs)[0m
[1;32m    973[0m [38;5;28;01mif[39;00m kind [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39m_dataframe_kinds:
[1;32m    974[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(data, ABCDataFrame):
[0;32m--> 975[0m         [38;5;28;01mreturn[39;00m [43mplot_backend[49m[38;5;241;43m.[39;49m[43mplot[49m[43m([49m[43mdata[49m[43m,[49m[43m [49m[43mx[49m[38;5;241;43m=[39;49m[43mx[49m[43m,[49m[43m [49m[43my[49m[38;5;241;43m=[39;49m[43my[49m[43m,[49m[43m [49m[43mkind[49m[38;5;241;43m=[39;49m[43mkind[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    976[0m     [38;5;28;01melse[39;00m:
[1;32m    977[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mplot kind [39m[38;5;132;01m{[39;00mkind[38;5;132;01m}[39;00m[38;5;124m can only be used for data frames[39m[38;5;124m"[39m)

File [0;32m~/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/pandas/plotting/_matplotlib/__init__.py:71[0m, in [0;36mplot[0;34m(data, kind, **kwargs)[0m
[1;32m     69[0m         kwargs[[38;5;124m"[39m[38;5;124max[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;28mgetattr[39m(ax, [38;5;124m"[39m[38;5;124mleft_ax[39m[38;5;124m"[39m, ax)
[1;32m     70[0m plot_obj [38;5;241m=[39m PLOT_CLASSES[kind](data, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m---> 71[0m [43mplot_obj[49m[38;5;241;43m.[39;49m[43mgenerate[49m[43m([49m[43m)[49m
[1;32m     72[0m plot_obj[38;5;241m.[39mdraw()
[1;32m     73[0m [38;5;28;01mreturn[39;00m plot_obj[38;5;241m.[39mresult

File [0;32m~/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/pandas/plotting/_matplotlib/core.py:501[0m, in [0;36mMPLPlot.generate[0;34m(self)[0m
[1;32m    499[0m [38;5;28mself[39m[38;5;241m.[39m_compute_plot_data()
[1;32m    500[0m fig [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mfig
[0;32m--> 501[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_make_plot[49m[43m([49m[43mfig[49m[43m)[49m
[1;32m    502[0m [38;5;28mself[39m[38;5;241m.[39m_add_table()
[1;32m    503[0m [38;5;28mself[39m[38;5;241m.[39m_make_legend()

File [0;32m~/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/pandas/plotting/_matplotlib/core.py:1346[0m, in [0;36mScatterPlot._make_plot[0;34m(self, fig)[0m
[1;32m   1343[0m [38;5;28;01melse[39;00m:
[1;32m   1344[0m     label [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m   1345[0m scatter [38;5;241m=[39m ax[38;5;241m.[39mscatter(
[0;32m-> 1346[0m     [43mdata[49m[43m[[49m[43mx[49m[43m][49m[38;5;241m.[39mvalues,
[1;32m   1347[0m     data[y][38;5;241m.[39mvalues,
[1;32m   1348[0m     c[38;5;241m=[39mc_values,
[1;32m   1349[0m     label[38;5;241m=[39mlabel,
[1;32m   1350[0m     cmap[38;5;241m=[39mcmap,
[1;32m   1351[0m     norm[38;5;241m=[39mnorm,
[1;32m   1352[0m     s[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39ms,
[1;32m   1353[0m     [38;5;241m*[39m[38;5;241m*[39m[38;5;28mself[39m[38;5;241m.[39mkwds,
[1;32m   1354[0m )
[1;32m   1355[0m [38;5;28;01mif[39;00m cb:
[1;32m   1356[0m     cbar_label [38;5;241m=[39m c [38;5;28;01mif[39;00m c_is_column [38;5;28;01melse[39;00m [38;5;124m"[39m[38;5;124m"[39m

File [0;32m~/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/frame.py:4102[0m, in [0;36mDataFrame.__getitem__[0;34m(self, key)[0m
[1;32m   4100[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mcolumns[38;5;241m.[39mnlevels [38;5;241m>[39m [38;5;241m1[39m:
[1;32m   4101[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_getitem_multilevel(key)
[0;32m-> 4102[0m indexer [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcolumns[49m[38;5;241;43m.[39;49m[43mget_loc[49m[43m([49m[43mkey[49m[43m)[49m
[1;32m   4103[0m [38;5;28;01mif[39;00m is_integer(indexer):
[1;32m   4104[0m     indexer [38;5;241m=[39m [indexer]

File [0;32m~/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/indexes/base.py:3812[0m, in [0;36mIndex.get_loc[0;34m(self, key)[0m
[1;32m   3807[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(casted_key, [38;5;28mslice[39m) [38;5;129;01mor[39;00m (
[1;32m   3808[0m         [38;5;28misinstance[39m(casted_key, abc[38;5;241m.[39mIterable)
[1;32m   3809[0m         [38;5;129;01mand[39;00m [38;5;28many[39m([38;5;28misinstance[39m(x, [38;5;28mslice[39m) [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m casted_key)
[1;32m   3810[0m     ):
[1;32m   3811[0m         [38;5;28;01mraise[39;00m InvalidIndexError(key)
[0;32m-> 3812[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m   3813[0m [38;5;28;01mexcept[39;00m [38;5;167;01mTypeError[39;00m:
[1;32m   3814[0m     [38;5;66;03m# If we have a listlike key, _check_indexing_error will raise[39;00m
[1;32m   3815[0m     [38;5;66;03m#  InvalidIndexError. Otherwise we fall through and re-raise[39;00m
[1;32m   3816[0m     [38;5;66;03m#  the TypeError.[39;00m
[1;32m   3817[0m     [38;5;28mself[39m[38;5;241m.[39m_check_indexing_error(key)

[0;31mKeyError[0m: 'mass'

